# Generated by Django 4.0 on 2021-12-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Slug', models.CharField(max_length=255)),
                ('Parent', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
        ),
    ]
