# Generated by Django 4.0.1 on 2022-01-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_categories_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prd_is_featured',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='products',
            name='prd_is_popular',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
