# Generated by Django 4.0.1 on 2022-01-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_products_prd_brand_products_prd_oferpercentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prd_availabilityCount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='prd_color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='prd_size',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='prd_reviewsCount',
            field=models.IntegerField(default=0),
        ),
    ]
