# Generated by Django 4.0.1 on 2022-01-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_products_prd_availabilitycount_products_prd_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
