# Generated by Django 4.0.1 on 2022-01-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0013_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brandLogo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
