# Generated by Django 4.0.1 on 2022-01-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_color_size_products_prd_colortable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prd_availabilityCount',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='prd_color',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='prd_colorTable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.color'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prd_size',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='prd_sizeTable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.size'),
        ),
    ]
