# Generated by Django 4.0.1 on 2022-01-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0017_alter_products_prd_availabilitycount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, max_length=100)),
                ('strike_price', models.IntegerField(default=0, max_length=100)),
                ('gst', models.CharField(default='', max_length=100)),
                ('currency', models.CharField(default='', max_length=100)),
                ('width', models.CharField(default='', max_length=100)),
                ('height', models.CharField(default='', max_length=100)),
                ('weight', models.CharField(default='', max_length=100)),
                ('shipping_fee', models.CharField(default='', max_length=100)),
                ('availabilityCount', models.CharField(default='', max_length=100)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.products')),
                ('sizeTable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.size')),
            ],
        ),
    ]
