# Generated by Django 4.0.1 on 2022-01-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0018_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variants',
            name='strike_price',
            field=models.IntegerField(default=0),
        ),
    ]
