# Generated by Django 4.0.1 on 2022-01-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0019_alter_variants_price_alter_variants_strike_price'),
        ('store', '0007_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.variants'),
        ),
    ]
